---

sudo: false

language: php

php:
  - 7.1
  - 7.2
  - nightly

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=weak
    - SYMFONY_VERSION=3.2.x-dev

matrix:
  include:
    - env: SYMFONY_VERSION=3.3.x-dev
    - env: SYMFONY_VERSION=3.4.x-dev
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
  - bash ./.travis/exec-before.bash

install:
  - travis_retry composer require "symfony/symfony:${SYMFONY_VERSION}" $COMPOSER_FLAGS

script:
  - bin/simple-phpunit -vvv || bin/phpunit -vvv

after_script:
  - bash ./.travis/exec-after.bash
